apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: retrain
spec:
  # retrain every 5  minute
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: retrain
            image: buildpack-deps:curl
            args:
            - /bin/sh
            - -ec
            - curl -d -X POST http://train-service/data
          restartPolicy: Never
