apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: trainapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: trainapp
    spec:
      containers:
      - name: trainapp
        image: cowzurecontainerreg.azurecr.io/train_img:v54
        ports:
        - containerPort: 8000 # should match docker file
        env:
        - name: STORAGE_ACCT_NAME
          value: storageeacct
        - name: STORAGE_ACCT_KEY
          value: HGmIr4mrYOQlbRfxBjl8XnWXsb9y5VL39ZKc+MG9YflpqbyZKKI5BP/9+J/nZR4bfLMtvbRvPrAFwImbnMjPtw==
        - name: BLOB_CONTAINER_NAME
          value: blobcontainer
        - name: PREDICT_SERVICE_IP
          value: 23.99.129.184
        - name: HOST
          value: https://edgeserverdatabaseaccount.documents.azure.com:443/
        - name: MASTER_KEY
          value: ZdYMlvNLJQHsVmInhEeNafE1vNEeRNjl5s4LaDR0Vz7JI7Bw2kHfXu0LznwY8UG36q3Ge7MqaYVQcJyBixcSvA==
        - name: DATABASE_ID
          value: edgeserverdatabase
        - name: COLLECTION_ID
          value: regularsensordatacollection
