apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: trainapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: trainapp
    spec:
      containers:
      - name: trainapp
        image: cowzurecontainerreg.azurecr.io/train_img:v8
        ports:
        - containerPort: 8000 # should match docker file
        env:
        - name: STORAGE_ACCT_NAME
          value: storageeacct
        - name: STORAGE_ACCT_KEY
          value: 0nctwAhQ2PdTGABwe3ciJMPHQsRAZlILrRccCaXKe8LK0MOBMWH6qGP/8qTvEpUlidUpjLMj5wKJ0tu/Cg7MCQ==
        - name: BLOB_CONTAINER_NAME
          value: blobcontainer
        - name: PREDICT_SERVICE_IP
          value: 40.121.219.50
