apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: predictapp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: predictapp
    spec:
      containers:
      - name: predictapp
        image: cowzurecontainerreg.azurecr.io/predict_img:v54
        ports:
        - containerPort: 8080 # should match docker file
        env:
        - name: STORAGE_ACCT_NAME
          value: storageeacct
        - name: STORAGE_ACCT_KEY
          value: HGmIr4mrYOQlbRfxBjl8XnWXsb9y5VL39ZKc+MG9YflpqbyZKKI5BP/9+J/nZR4bfLMtvbRvPrAFwImbnMjPtw==
        - name: BLOB_CONTAINER_NAME
          value: blobcontainer