apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: predictapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: predictapp
    spec:
      containers:
      - name: predictapp
        image: cowzurecontainerreg.azurecr.io/predict_img:v5
        ports:
        - containerPort: 8080 # should match docker file
        env:
        - name: STORAGE_ACCT_NAME
          value: storageeacct
        - name: STORAGE_ACCT_KEY
          value: +aROPLVyqGPkM9irWkq2LDB8NtThmTd+f75TkU/XVTkWFnPBOTCQeNjLou7N1F+kYdgDLwhOZoe5msOcntd2uA==
        - name: BLOB_CONTAINER_NAME
          value: blobcontainer