apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: predictapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: predictapp
    spec:
      containers:
      - name: predictapp
        image: cowzurecontainerreg.azurecr.io/predict_img:v1
        ports:
        - containerPort: 8080 # should match docker file
